### ISSUE TITLE
Add standard classifiers

### ISSUE THREAD

**Issue by mittinatten** [freesasa/freesasa-python#1]
Add classifiers so that a user can get per-residue, and per-residue-type SASA without resorting to select statements.

**Comment by mittinatten** [comment]
Fixed by 5abff49e6e0e5017923c8a

**Comment by ehfd** [comment]
This is also pretty needed preferably with integration with Relative SASA per-residue.

**Comment by mittinatten** [comment]
With the solution proposed in #3 this can easily be extracted from the results there. Per-residue is already there and per-residue-type is a trivial summation over the results. One could possibly add a wrapper that does the summation for the user.

**Comment by ehfd** [comment]
Let's close this unless there is a plan for per-residue-type. Thank you.
