### ISSUE TITLE
AssertError from freesasa.structureArray due to classifier

### ISSUE THREAD

**Issue by bieniekmateusz** [freesasa/freesasa-python#10]
I received an AssertionError due to the classifier:
```
  File "freesasa.pyx", line 814, in freesasa.structureArray
  File "freesasa.pyx", line 556, in freesasa.Structure.setRadiiWithClassifier
  File "freesasa.pyx", line 577, in freesasa.Structure.setRadii
AssertionError
```

Do you think it would be good to update the documentation about http://freesasa.github.io/python/functions.html#freesasa.structureArray that it is possible? I looked up the documentation and assumed that the error must be due to the config instead because the classifier is not mentioned. 

Thanks, Mat

**Comment by bieniekmateusz** [comment]
I think I read it the wrong way.

**Comment by bieniekmateusz** [comment]
I found what the problem is. The structureArray does not work for a .pdb with a single frame. I think if that is the case, there should be a cleaner error than:
`File "freesasa.pyx", line 577, in freesasa.Structure.setRadii`

Something like "only one frame found, please use freesasa.Structure() function instead" etc.

**Comment by bieniekmateusz** [comment]
This turned out to be false. Something is causing this issue.

I've tried to figure out which atom has an issue by checking the Classifier.radius on each atom, but all of them were fine:
```
import freesasa
c =freesasa.Classifier('amber_config.txt')
import MDAnalysis as mda
u = mda.Universe('complex.pdb')
aee = u.select_atoms('resname AEE')
for atom in aee:
	print(atom.resname, atom.name)
	c.radius(atom.resname, atom.name)
# getting radius
for atom in u.atoms:
	c.radius(atom.resname, atom.name)
```

[amber_config.txt](https://github.com/freesasa/freesasa-python/files/4371082/amber_config.txt)
[complex.tar.gz](https://github.com/freesasa/freesasa-python/files/4371091/complex.tar.gz)

**Comment by bieniekmateusz** [comment]
Just to clarify, when I compile the same version of freesasa and use the command line, it works fine:
`./freesasa --config-file=amber_config.txt complex.pdb`

Thanks, Mat

**Comment by bieniekmateusz** [comment]
I've been mistaking the radii -1 as not an error. It seems that I need some more general rule for the config file in order to capture non-standard residues/ligands.

**Comment by mittinatten** [comment]
I was just about to write that the assertion on line 577 checks for negative radii :) Let me know if you have further troubles!

**Comment by bieniekmateusz** [comment]
Thanks, I am slowly getting a grip of it. 

Maybe the assertion error could give slightly more details about which atom's radius could not be resolved.

Cheers, Mat
