### ISSUE TITLE
Build a conda package?

### ISSUE THREAD

**Issue by ghost** [freesasa/freesasa-python#22]
I know some orgs might prefer conda package than pip. Any idea making one? 
I'm not sure whether technically/ethically only the owner can build one or anyone can do that.

**Comment by mittinatten** [comment]
I have never published to Conda, but I assume it wouldn't be that much extra config. I am one day from going on vacation, but will get back to this in August.

**Comment by mittinatten** [comment]
Hopefully it just means adding one line here: https://github.com/freesasa/freesasa-python/blob/8d8ec227c0981e20c9be6ae23515ce421cc38b61/.travis.yml#L61 and here: https://github.com/freesasa/freesasa-python/blob/8d8ec227c0981e20c9be6ae23515ce421cc38b61/appveyor.yml#L102

**Comment by pgbarletta** [comment]
Hi @mittinatten,
I created a [recipe](https://github.com/pgbarletta/staged-recipes) and I'd like to add it to conda forge. 

Are you ok with it, and if so, do you want me to add you as a maintainer as well?

**Comment by mittinatten** [comment]
Great, thank you! As long as it's just cloning the pypi package I don't think I need to be a maintainer. But when it's published, could you perhaps create a PR here with an update to the README with install instructions?

**Comment by mittinatten** [comment]
Solved ✅
