### ISSUE TITLE
Identifying solvent-exposed cysteines with freesasa

### ISSUE THREAD

**Issue by areyesromero** [freesasa/freesasa-python#25]
Dear Simon,
I am new to using freesasa.
My task is to print out the number of solvent-exposed cysteines of a given protein. I will have to iterate the same operation for all the pdb files contained in a folder. The script is this: 

"import os
import freesasa
from pymol import cmd
from Bio.PDB import PDBParser

path="/Users/atilioreyesromero/Desktop"
structure = freesasa.Structure(os.path.join(path,"1u2q.pdb"))
result = freesasa.calc(structure)
residue_area = result.residueAreas()
total = dict(map(lambda x: (x[0], x[1].relativeTotal), residue_area['A'].items()))
print(total)"

As you may notice, this method prints values for all aminoacids: do you know a way to filter only those of interest?
Best regards

**Comment by ghost** [comment]
how about this? 

```python
import os
import freesasa

path="/Users/atilioreyesromero/Desktop"
structure = freesasa.Structure(os.path.join(path,"1u2q.pdb"))
result = freesasa.calc(structure)
freesasa.selectArea(["cys_SASA, resn cys"], structure, result)
```

**Comment by areyesromero** [comment]
I tested the script and as output I have: {'cys_SASA': 102.02858367516248} which is the sum SASA across all of the three cysteine residues. 
Instead the expected outcome should be a dictionary for each residue, for example:

{'11': SASA value cys11;
'16': SASA value cys16;
'53': SASA value cys53}

**Comment by areyesromero** [comment]
I found a temporary solution with Biopython:

#import the modules
import os
import freesasa
from Bio.PDB import *

pdb = PDBList()
pdb.retrieve_pdb_file("1U2P", pdir=".", file_format="pdb")
parser = PDBParser(PERMISSIVE=True, QUIET=True)
structure = parser.get_structure("1U2P","pdb1u2p.ent")

model = structure[0]
chain = model['A']

#append the cysteine index
CYS_list=[]
for i,residue in zip(chain.get_residues(),model.get_residues()):
    if i.get_resname() == "CYS":
        CYS_list.append(residue.get_full_id()[3][1])

#calculate the SASA for each cysteine
path="/Users/arr4007/Desktop"
structure = freesasa.Structure(os.path.join(path,"1u2p.pdb"))
result = freesasa.calc(structure)

for CYS in CYS_list:
    print(CYS, freesasa.selectArea(["CYS, chain A and resi " + str(CYS) ], structure, result))

result = freesasa.calc(structure)
freesasa.selectArea(["cys_SASA, resn cys"], structure, result)

In this case the output is:

11 {'CYS': 3.8607456448379214}
16 {'CYS': 4.53132567368472}
53 {'CYS': 93.63651235663983}

What do you think? Would that there be any room for simplifications in string formulation?

**Comment by areyesromero** [comment]
I found a temporary solution with Biopython:

```ruby
#import the modules
import os
import freesasa
from Bio.PDB import *

pdb = PDBList()
pdb.retrieve_pdb_file("1U2P", pdir=".", file_format="pdb")
parser = PDBParser(PERMISSIVE=True, QUIET=True)
structure = parser.get_structure("1U2P","pdb1u2p.ent")

model = structure[0]
chain = model['A']

#append the cysteine index
CYS_list=[]
for i,residue in zip(chain.get_residues(),model.get_residues()):
if i.get_resname() == "CYS":
CYS_list.append(residue.get_full_id()[3][1])

#calculate the SASA for each cysteine
path="/Users/arr4007/Desktop"
structure = freesasa.Structure(os.path.join(path,"1u2p.pdb"))
result = freesasa.calc(structure)

for CYS in CYS_list:
print(CYS, freesasa.selectArea(["CYS, chain A and resi " + str(CYS) ], structure, result))

result = freesasa.calc(structure)
freesasa.selectArea(["cys_SASA, resn cys"], structure, result)
```

In this case the output is:

11 {'CYS': 3.8607456448379214}
16 {'CYS': 4.53132567368472}
53 {'CYS': 93.63651235663983}

What do you think? Would that there be any room for simplifications in string formulation?

**Comment by ghost** [comment]
I'm not familiar with BioPython, so I will just stick to freesasa functionalities. 

```python
residue_name = "CYS"
residue_idx = set()

for atom_idx in range(structure.nAtoms()):
    if structure.residueName(atom_idx) == residue_name:
        residue_idx.add(structure.residueNumber(atom_idx).strip())

result = freesasa.calc(structure).residueAreas()['A']

for idx in residue_idx:
    print("residue name: %s, residue ID: %s, SASA: %f" %(residue_name, idx, result[idx].total))
```

**Comment by mittinatten** [comment]
Hi,
The solution by @htian97 should work fine. There is a built in function that does more or less the same, which I guess is the simplest solution http://freesasa.github.io/python/classes.html#freesasa.Result.residueAreas

**Comment by mittinatten** [comment]
Your selection version obviously works fine too, @areyesromero, but the selection code is relatively slow. It's not noticeable for only a couple of selections, but might make a difference if you are selecting all residues in the protein, one by one, for instance. Then it's better to use either the builtin function, or index manually as above, if you need something  other than matching on residues, in the future.

**Comment by areyesromero** [comment]
I took note and streamlined the lines using only freesasa and now looks as follows

```ruby
import os
import freesasa

my_pdb,path, aminoacid, chain = "1u2p.pdb", "/Users/arr4007/Desktop", "CYS", "A"

structure = freesasa.Structure(os.path.join(path,my_pdb))
result = freesasa.calc(structure)

residueAreas = result.residueAreas() 
chain = residueAreas[chain]

for v in chain.values():
    if v.residueType == aminoacid:
        print(aminoacid, v.residueNumber, v.total)
```

which gives: 
CYS 11 3.8607456448379214
CYS 16 4.53132567368472
CYS 53 93.63651235663983


Thanks @mittinatten and @htian97 for your feedbacks. Both solutions helped me.

**Comment by mittinatten** [comment]
Glad to help  🙂
