### ISSUE TITLE
Log Information

### ISSUE THREAD

**Issue by xiaolinpan** [freesasa/freesasa-python#27]
Many thanks for your open-source code! Could you help me close the freesasa warning output?

`FreeSASA: warning: atom 'UNL H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'UNL H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'UNL H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'UNL H' unknown, guessing element is ' H', and radius 1.100 A
`

**Comment by mittinatten** [comment]
Hi, you can turn off warnings using the option `--no-warnings`.

**Comment by mittinatten** [comment]
Sorry, that's for the CLI. For Python you can use `freesasa.setVerbosity` (https://freesasa.github.io/python/functions.html#freesasa.setVerbosity)

**Comment by xiaolinpan** [comment]
Thank you very much!
