### ISSUE TITLE
Add chain-groups support

### ISSUE THREAD

**Issue by pgbarletta** [freesasa/freesasa-python#29]
Hi!
I'd like to have this feature implemented in the python bindings. I would mimic the C impementation and define a new wrapper function `get_structures()` that:

1. takes the selection string as an argument, or maybe I should add the selection string to the `defaultStructureArrayOptions` dict (whichever you prefer)
2. validates its input
3. calls `freesasa_structure_array()` (if `separate-chains` or `separate-models` were specified), or `freesasa_structure_from_pdb()` (default) 
4. then calls `freesasa_structure_get_chains`() if the user selected `chain-groups`. It should probably err out if both `separate-chains` and  `chain-groups` were specified.

I'm probably missing quite a few other things, but anyway, would this PR be welcomed?

**Comment by mittinatten** [comment]
Hi,
That sounds like a useful feature! A PR would  be welcome (including tests). Not sure what's the best name for the function, but I guess we have some time to think about that.
