### ISSUE TITLE
Allow calculating relative SASA

### ISSUE THREAD

**Issue by mittinatten** [freesasa/freesasa-python#3]
As in CLI.

**Comment by ehfd** [comment]
This is a very critical issue. I have requested to include [FreeSASA](https://github.com/iodide-project/pyodide/issues/691) in Pyodide for decrippling various classes in Bio.PDB in client-side web applications. This program is the only true viable open-source library for SASA related tasks and relative SASA is a very important concept. It would be great if this has been implemented.

**Comment by mittinatten** [comment]
It shouldn't be too difficult to add, I will look into it after the summer holidays.

**Comment by ehfd** [comment]
Great. Thank you. Not totally urgent.

**Comment by mittinatten** [comment]
I have sketched a simple solution in #14, where you get a dictionary result
```python
residueAreas = result.residueAreas()
a76 = residueAreas['A']['76'] # Residue area for residue 76 in chain A
a76.total # total area for residue in Å^2
a76.relativeTotal # relative total area, value in range 0 to 1, sometimes larger than 1 if very exposed or at end of chains
```
You can see the diff in the PR for all the available fields. I will add documentation eventually.

Is this a viable solution? It's the first thing I could think of, so there are probably other solutions that are more intuitive and/or user-friendly.

**Comment by ehfd** [comment]
Let me look into it and help.

**Comment by ehfd** [comment]
I'll try pulling it and compare it with other implementations of relative SASA.

**Comment by mittinatten** [comment]
Great! I just added a few more fields to the `ResidueArea` class: 
```python
a76.residueName # = 'ALA', 'GLY', etc`  
a76.hasRelativeAreas # = True: was able to calculate rel areas, 
                     # False: no reference area available (exotic resiudes, classifier without relative areas, etc)
```

**Comment by ehfd** [comment]
As the tests did pass, both #1 and this can be closed.

**Comment by mittinatten** [comment]
Unfortunately not, Freesasa only supports a basic subset of the pymol interface.

**Comment by mittinatten** [comment]
Some selections can be pretty easily handled with a custom classifier, passed to [freesasa.classifyResults()](http://freesasa.github.io/python/functions.html#freesasa.classifyResults). But it's of course more cumbersome than using a DSL as in pymol.

**Comment by mittinatten** [comment]
The release is out (2.1.0) and the docs updated.
