### ISSUE TITLE
Python 3.11 support?

### ISSUE THREAD

**Issue by hoodmane** [freesasa/freesasa-python#32]
I think all that's needed is to recythonize with a Cython that supports Python 3.11.

Also, I think it would be nice if the sdist included the cython sources so we could delete them and recythonize to make it work in Python 3.11.

**Comment by mittinatten** [comment]
Hi, thanks for bringing this up. A fix is on its way.

**Comment by mittinatten** [comment]
I have included all the cython sources in the source package, thanks for pointing that out and updated the package to support 3.11.

Seems I can't build python 3.11 binaries for Mac OS with my CI setup, so there one will have to rely on the sdist for now. A pre-release is available here https://pypi.org/project/freesasa/2.2.0b2/. I think this version is ready for production (it's been in prerelease for a year now) so if everything looks ok for you, I will publish 2.2.0.

**Comment by hoodmane** [comment]
Wow that was fast thanks! I just looked at a few other packages and most of them didn't have cython sources in their sdists. @henryiii is this something I have the right to tell people they ought to do?

I will try to build your tip of tree against Pyodide/Python 3.11 and let you know if it works.

**Comment by hoodmane** [comment]
Okay, no problems building a cp311-emscripten freesasa wheel from tip of tree. I haven't tested it yet I'll try to get to that later today.

**Comment by hoodmane** [comment]
Looks like everything works:
```console
$ pip install ~/pyodide/pyodide-build
... lots of output
Successfully installed ...
$ USE_CYTHON=1 pyodide build
... lots of output
Successfully built /home/hood/freesasa-python/dist/freesasa-2.2.0b2-cp311-cp311-emscripten_3_1_25_wasm32.whl
$ pyodide venv .venv-pyodide
Creating Pyodide virtualenv at .venv-pyodide
... Configuring virtualenv
... Installing standard library
Successfully created Pyodide virtual environment!
$ pip install dist/freesasa*.whl
Looking in links: /home/hood/pyodide/dist
Processing ./dist/freesasa-2.2.0b2-cp311-cp311-emscripten_3_1_25_wasm32.whl
Installing collected packages: freesasa
Successfully installed freesasa-2.2.0b2
$ python -m test
Can't import Bio.PDB, tests skipped
.........
----------------------------------------------------------------------
Ran 9 tests in 0.254s
```

**Comment by hoodmane** [comment]
Thanks again @mittinatten!

**Comment by mittinatten** [comment]
Great! Thanks again for raising this issue.

**Comment by henryiii** [comment]
It's best to either avoid including Cython sources, or to at least try to rebuild and only use the Cython source if Cython is missing. Historically, it was hard to ensure a dependency was present during the build process. Now, with pyproject.toml, it is trivial, so just depending on Cython being present is much safer.

You pretty much need a new patch release of Cython for everything - new Python releases, new OS releases, new compilers, etc.
