### ISSUE TITLE
Using FreeSASA for multiple PDB files

### ISSUE THREAD

**Issue by YairFrank** [freesasa/freesasa-python#6]
Hello,
I want to calculate SASA by specific chains (using the function "selectArea") in multiple PDB files.
Is there any way to use variables instead of explicit names of chains?
I tried to run the script, in two ways.
First by concatenating strings:
`dict = freesasa.selectArea([k+', chain '+k[0]+'+'+k[1]], structure, result)`
second by putting variables in the string:
`dict = freesasa.selectArea(['%s, chain %s+%s' % (k, k[0], k[1])], structure, result)`
Both ways gave this exception:

> Exception: Error parsing '

>, chain  +

> '

Any advice would be greatly appreciated.

**Comment by mittinatten** [comment]
This should work, are you sure k has the right value?

**Comment by YairFrank** [comment]
Yes, k represents a string. "AB" for example.

**Comment by mittinatten** [comment]
What do you get if you simply print `k+', chain '+k[0]+'+'+k[1]`?

**Comment by YairFrank** [comment]
Ok, that's what I missed. I forgot to strip them. They had '\n'.
Thank you for helping.
