### ISSUE TITLE
Using freesasa.structureArray() to separate models/chains

### ISSUE THREAD

**Issue by leonchas17** [freesasa/freesasa-python#8]
The documentation for the python bindings suggests that the function FreeSASA.structureArray() can be used to split a pdb with several models and/or several chains. However it's not clear to me what the correct syntaxes would be. I've tried things like
```python
structure = freesasa.structureArray("1aqg.pdb")
structure.defaultStructureArrayOptions['separate-models'] = True
```
because defaultStructureArrayOptions is supposed to be a dictionary, but clearly it hasn't worked.
Any tips would be appreciated.

leonchas17

**Comment by mittinatten** [comment]
Hi, I forgot about this function, that would have solved your previous issue (#7). It's been a while since I used the Python module myself :)  

The default options are what will be used if nothing is specified, to change what happens, you should use the following call 
```python
structureArray = freesasa.structureArray("1agq.pdb", yourOptionsDictionary)
```
see http://freesasa.github.io/python/functions.html#freesasa.structureArray.

**Comment by leonchas17** [comment]
Cool, I´m posting an implementation example based on a pdb that has both several models and two chains in each model:

```python
structureArray = freesasa.structureArray("1d7q.pdb", options = { 'separate-chains': True, 'separate-models': True})
for model in structureArray:
    print dir(model)
    result = freesasa.calc(model)
    print model.chainLabel(1) , result.totalArea()

```
(this one is using python 2 style syntax)
It took me a while to realize that the options dictionary _had_ to be named ''options''.  ;)
The 'model.chainLabel(1)' is a workaround to use the chainlabel of the atom of index 1 of each chain in order to identify the chain.
This produces an array of Structure objects, one for each chain in each model. If one omits the  " 'separate-models': True" dictionary entry and the pdb file has, for instance, two chains per model, one gets an array of two Structure objects. I´m I correct in assuming that those chain will correspond to the first model in the file?
Likewise, if one omits the " 'separate-chains': True" one only gets as many Structure objects as there were models, i. e. 20 in this example.

**Comment by mittinatten** [comment]
Your assumptions are correct. You don't have to name the options object at all though (I'm surprised your code works at all), you can simply pass it in anonymously:
```python
# use an anonymous object
structureArray = freesasa.structureArray("1d7q.pdb", { 'separate-chains': True, 'separate-models': True})

# or define it first, which ever is most convenient
myOptions = { 'separate-chains': True, 'separate-models': True})
structureArray = freesasa.structureArray("1d7q.pdb", myOptions)
```
The test code illustrates how the different combinations of parameters work as well:
https://github.com/freesasa/freesasa-python/blob/master/test.py#L172

**Comment by mittinatten** [comment]
I'll close this for now, feel free to reopen if anything comes up.
