### ISSUE TITLE
Residue index

### ISSUE THREAD

**Issue by YairFrank** [freesasa/freesasa-python#9]
Hi,
I saw that the property selector `resi` means a residue index. If I understood correctly, there's a difference between a residue index and a residue name. I wanted to calculate residues from different chains and probably that's why there is a need for residue indices. How can I find them?
Thank you

**Comment by mittinatten** [comment]
Hi,
`resi` corresponds to the `resSeq` field in PDB ATOM records (http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM). In a file with several chains more than one residue can have the same residue number. If you want to select residues from a specific chain you should use the `chain` selector, i.e. `chain a and resi 1-10`.

`resn` corresponds to `resName`, i.e. the three letter code for the amino acid (ALA, GLU, etc).

**Comment by YairFrank** [comment]
Thank you very much
